# Generated by Django 3.2 on 2021-05-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='flats',
            name='rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flats',
            name='sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flats',
            name='rate',
            field=models.CharField(max_length=20),
        ),
    ]
