# Generated by Django 3.2 on 2021-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210515_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='city_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='flats_id',
            field=models.IntegerField(default=1),
        ),
    ]
