# Generated by Django 3.2 on 2021-05-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_enquiry_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enquiry_us',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='city_id',
        ),
    ]
