# Generated by Django 3.2 on 2021-05-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_enquiry_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
